services:
  shelfmaster_front_app_stage:
    image: ghcr.io/amir-taheri-web/shelfmaster-front:latest
    container_name: shelfmaster_front_stage
    restart: always
    pull_policy: always
    ports:
      - "5000:5000"
    networks:
      - shelfmaster-front-stage

networks:
  shelfmaster-front-stage:
    external: true
