name: Continuous Deployment

on:
  push:
    branches: ["main"]

permissions:
  packages: write # ✅ Give GITHUB_TOKEN permission to push to GHCR
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "amir-taheri-web/shelfmaster-front:latest"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR # ✅ Uses correct authentication
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # or secrets.GHCR_PAT if we want to use our pat token(we can get this token from //private access token from https://github.com/settings/personal-access-tokens)

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            BASE_URL=${{ vars.BASE_URL }}
            NEXT_PUBLIC_BASE_URL=${{ vars.NEXT_PUBLIC_BASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment:
      name: staging
      url: https://shelfmaster.geeksec.fun
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_IP }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            cd ShelfMaster-front
            git pull origin main
            docker compose up -d
